### ISSUE TITLE
`RUSTDOC=cargo-callgraph cargo doc` panics on callgraph itself

### ISSUE THREAD

**Issue by jyn514** [robinmoussu/cargo-callgraph#6]
```
 Documenting lazy_static v1.4.0
thread 'rustc' panicked at 'could not lift for printing', compiler/rustc_middle/src/ty/print/pretty.rs:1907:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/option.rs:1260:5
   3: rustc_middle::ty::print::pretty::<impl core::fmt::Display for &rustc_middle::ty::consts::Const>::fmt
   4: core::fmt::write
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/fmt/mod.rs:1078:17
   5: std::io::Write::write_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/io/mod.rs:1519:15
   6: cargo_callgraph::extract_dependencies::render_dependencies
             at /home/joshua/src/rust/cargo-callgraph/extract_dependencies.rs:773:25
   7: cargo_callgraph::extract_dependencies::extract_and_render_dependencies
             at /home/joshua/src/rust/cargo-callgraph/extract_dependencies.rs:657:5
   8: cargo_callgraph::core::run_global_ctxt::{{closure}}
             at /home/joshua/src/rust/cargo-callgraph/core.rs:539:27
   9: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_data_structures/src/profiling.rs:570:9
  10: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_session/src/utils.rs:9:9
  11: cargo_callgraph::core::run_global_ctxt
             at /home/joshua/src/rust/cargo-callgraph/core.rs:536:5
  12: cargo_callgraph::core::run_core::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/joshua/src/rust/cargo-callgraph/core.rs:474:21
  13: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/passes.rs:725:42
  14: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_middle/src/ty/context.rs:1739:50
  15: rustc_middle::ty::context::tls::set_tlv
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_middle/src/ty/context.rs:1723:9
  16: rustc_middle::ty::context::tls::enter_context
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_middle/src/ty/context.rs:1739:9
  17: rustc_interface::passes::QueryContext::enter
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/passes.rs:725:9
  18: cargo_callgraph::core::run_core::{{closure}}::{{closure}}::{{closure}}
             at /home/joshua/src/rust/cargo-callgraph/core.rs:473:17
  19: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_data_structures/src/profiling.rs:570:9
  20: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_session/src/utils.rs:9:9
  21: cargo_callgraph::core::run_core::{{closure}}::{{closure}}
             at /home/joshua/src/rust/cargo-callgraph/core.rs:472:46
  22: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/queries.rs:415:19
  23: cargo_callgraph::core::run_core::{{closure}}
             at /home/joshua/src/rust/cargo-callgraph/core.rs:431:9
  24: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/interface.rs:196:13
  25: rustc_span::with_source_map
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_span/src/lib.rs:764:5
  26: rustc_interface::interface::create_compiler_and_run
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/interface.rs:190:5
  27: cargo_callgraph::core::run_core
             at /home/joshua/src/rust/cargo-callgraph/core.rs:430:5
  28: cargo_callgraph::main_options
             at /home/joshua/src/rust/cargo-callgraph/lib.rs:584:53
  29: cargo_callgraph::main_args::{{closure}}
             at /home/joshua/src/rust/cargo-callgraph/lib.rs:517:17
  30: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/util.rs:152:13
  31: scoped_tls::ScopedKey<T>::set
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  32: rustc_span::with_session_globals
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_span/src/lib.rs:93:5
  33: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/util.rs:150:9
  34: rustc_interface::util::scoped_thread::{{closure}}
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/compiler/rustc_interface/src/util.rs:125:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jyn514** [comment]
https://github.com/robinmoussu/cargo-callgraph/blob/27205d329412f9c69b274512f6302384013774da/extract_dependencies.rs#L773

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/blob/1c389ffef/compiler/rustc_middle/src/ty/print/pretty.rs#L1907

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/blob/1c389ffef/compiler/rustc_middle/src/ty/print/pretty.rs#L1844

**Comment by robinmoussu** [comment]
fixed
